const createIPCEventType = (message: string) => ({
	INVOKE: `${ message }_INVOKE`,
	RESPONSE: `${ message }_RESPONSE`
});

export const IPC_ACTIONS = {
	File: {
		REQUEST_OPEN_FILE_DIALOG: createIPCEventType("REQUEST_OPEN_FILE_DIALOG"),
		REQUEST_SAVE_FILE_DIALOG: createIPCEventType("REQUEST_SAVE_FILE_DIALOG"),
		REQUEST_SAVE_PROJECT: createIPCEventType("REQUEST_SAVE_PROJECT"),
		REQUEST_LOAD_META_DATA: createIPCEventType("REQUEST_LOAD_META_DATA")
	},
	Window: {
		REQUEST_CLOSE_WINDOW: createIPCEventType("REQUEST_CLOSE_WINDOW"),
		REQUEST_MINIMIZE_WINDOW: createIPCEventType("REQUEST_MINIMIZE_WINDOW"),
		REQUEST_MAXMINIZE_WINDOW: createIPCEventType("REQUEST_MAXIMIZE_WINDOW")
	}
};
